### ISSUE TITLE
Simplification cause Errors by Export

### ISSUE THREAD

**Issue by mightz1986** [giscafer/mapshaper-plus#1]
Hello,

after using the simplification of the geoJSON File, it cannot be exported in encoded echarts format:

Error: Uncaught TypeError: Cannot set property 'encodeOffsets' of null

**Comment by giscafer** [comment]
have you try http://www.mapshaper.org/ yet? Take a try and see whether did it causes the same Errors

**Comment by mightz1986** [comment]
Hello,

It only occurs, if I try to Export map data in Echarts format. Both: encoded and not.
Mapshaper.org does not have such an option
Regards,

**Comment by giscafer** [comment]
use this geojson file https://github.com/bartvde/geojson, no issue

**Comment by giscafer** [comment]
make sure your geoJSON File format is correct

**Comment by mightz1986** [comment]
Hello,

thank for your response. I have used this one http://code.highcharts.com/mapdata/ 

for example: Europe -> geoJson format

If I apply any Simplification it cause the error described above

**Comment by giscafer** [comment]
please make sure you internet is load all file when you open the demo:http://giscafer.com/mapshaper-plus/

open in browser,then press F12 button, check the console whether has any errors。

**i have try again and success too**

[use the data](http://code.highcharts.com/mapdata/):`mapdata->Custom—>Africa(geoJSON)`
