### ISSUE TITLE
Export ECharts got undefined

### ISSUE THREAD

**Issue by Ovilia** [giscafer/mapshaper-plus#3]
I imported this GeoJSON data:
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              107.8912353515625,
              30.314802211415493
            ],
            [
              107.82943725585938,
              30.260253384089417
            ],
            [
              107.88848876953125,
              30.223475116500158
            ],
            [
              107.97225952148438,
              30.278044377800153
            ],
            [
              108.10409545898438,
              30.370505537135568
            ],
            [
              107.8912353515625,
              30.314802211415493
            ]
          ]
        ]
      }
    }
  ]
}
```

The polygon is rendered correctly in the website, but when export with Echarts-map-json or Echarts-map-js, the content is always `undefined`.

<img width="1440" alt="2019-01-10 2 38 34" src="https://user-images.githubusercontent.com/779050/50950674-a502c800-14e5-11e9-983e-01778e213f20.png">

**Comment by giscafer** [comment]
https://github.com/giscafer/mapshaper-plus/blob/8f0a1e9e2d9adc08b9110c93c8753ecf2a27c5c1/encode.js#L30

data convert by
https://github.com/giscafer/mapshaper-plus/blob/8f0a1e9e2d9adc08b9110c93c8753ecf2a27c5c1/mapshaper.js#L9121

![tim 20190110185701](https://user-images.githubusercontent.com/8676711/50964205-9b8b5700-1509-11e9-882c-be94572a4081.png)


the encode only support the features of map,such as [geometryProvince/11.json](https://raw.githubusercontent.com/longwosion/geojson-map-china/master/geometryProvince/11.json)

**Comment by giscafer** [comment]
```json
{"type":"GeometryCollection","geometries":[{"type":"Polygon","coordinates":["@@Ǵ²ōýë¯·¾°"],"encodeOffsets":[[110481,31043]]}],"UTF8Encoding":true}

```

already fixed https://github.com/giscafer/mapshaper-plus/commit/0fea2de28b21ca558e214f3441b2fdfb9ce1e577

**Comment by Ovilia** [comment]
WoW! So efficient! Thanks!

**Comment by Ovilia** [comment]
@giscafer I tried again, and the ECharts JSON format has been fixed, but the ECharts JS format still got `undefined`.

**Comment by giscafer** [comment]
@Ovilia I confirm is normal,see gif:

![3333](https://user-images.githubusercontent.com/8676711/51048371-bfcc5e00-1605-11e9-9866-64a33da622cc.gif)
